language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip3 install -r requirements.txt
before_script:
  - ./setup.sh
  - cp src/default_config.py src/config.py
script:
  - python3 src/test_user_data_access.py

