language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip3 install -r requirements.txt
before_script:
  - ./setup.sh
  - cp app/default_config.py app/config.py
script:
  - python3 app/test_user_data_access.py

