language: python
branches:
  only:
    - master
    - development
python:
  - "3.6"
services:
  - postgresql
install:
  - pip3 install -r requirements.txt
before_script:
  - ./setup.sh
script:
  - python3 -m unittest discover -s app
